# Generated by Django 3.0.4 on 2020-03-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='ECommerce.Product'),
        ),
    ]
