# Generated by Django 3.0.4 on 2020-03-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0003_auto_20200327_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_field',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Not Shipped', 'Not Shipped'), ('Padding', 'Padding')], max_length=30, null=True),
        ),
    ]
