# Generated by Django 3.0.4 on 2020-03-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0005_auto_20200327_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('InDoor', 'InDoor'), ('Out Door', 'Out Door')], max_length=40, null=True),
        ),
    ]
