# Generated by Django 3.0.4 on 2020-04-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0007_auto_20200401_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pic_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
