# Generated by Django 3.0.4 on 2020-04-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0008_customer_pic_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pic_profile',
        ),
    ]
