# Generated by Django 3.0.4 on 2020-04-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0009_remove_customer_pic_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pic_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
