# Generated by Django 3.0.4 on 2020-04-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0010_customer_pic_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pic_profile',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=''),
        ),
    ]
